name: Continuous Integration with GitHub, GitHub Actions and Docker Hub

on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3

     - name: Log in to Docker Hub
       uses: docker/login-action@v3.0.0
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
     
     - name: Setup Java JDK
       uses: actions/setup-java@v4.0.0
       with:
         java-version: '21'
         distribution: 'adopt'
         cache: maven
     - name: Build Application Jar
       working-directory: ./rest-react-java/server
       run: mvn clean package -DskipTests
       
     - name: Docker Compose Build
       working-directory: ./rest-react-java
       run: docker compose build

     - name: Push to Docker Hub Container Registry
       run: |
         docker tag rest-react-java-server:latest ${{ secrets.DOCKER_USERNAME }}/rest-react-java-server:latest
         docker tag rest-react-java-server:latest ${{ secrets.DOCKER_USERNAME }}/rest-react-java-server:${{github.run_id}}
         
         docker push ${{ secrets.DOCKER_USERNAME }}/rest-react-java-server:latest
         docker push ${{ secrets.DOCKER_USERNAME }}/rest-react-java-server:${{github.run_id}}