name: .NET 8 Continuous Integration with GitHub, GitHub Actions and Docker Hub

on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3

     - name: Log in to Docker Hub
       uses: docker/login-action@v3.0.0
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

     - name: Docker Compose Build
       working-directory: ./rest-react-dotnet/server/RestWithASPNETErudio
       run: docker compose build

     - name: Push to Docker Hub Container Registry
       run: |
         docker tag rest-react-dotnet-server:latest ${{ secrets.DOCKER_USERNAME }}/rest-react-dotnet-server:latest
         docker tag rest-react-dotnet-server:latest ${{ secrets.DOCKER_USERNAME }}/rest-react-dotnet-server:${{ github.run_id }}
         
         docker push ${{ secrets.DOCKER_USERNAME }}/rest-react-dotnet-server:latest
         docker push ${{ secrets.DOCKER_USERNAME }}/rest-react-dotnet-server:${{ github.run_id }}
         
         docker tag rest-react-dotnet-server-db:latest ${{ secrets.DOCKER_USERNAME }}/rest-react-dotnet-server-db:latest
         docker tag rest-react-dotnet-server-db:latest ${{ secrets.DOCKER_USERNAME }}/rest-react-dotnet-server-db:${{ github.run_id }}
         
         docker push ${{ secrets.DOCKER_USERNAME }}/rest-react-dotnet-server-db:latest
         docker push ${{ secrets.DOCKER_USERNAME }}/rest-react-dotnet-server-db:${{ github.run_id }}